### ISSUE TITLE
moveit! problem.

### ISSUE THREAD

**Issue by QuartzYan** [RobotnikAutomation/phantomx_reactor_arm#3]
hi guys!! I have a PhantomX Reactor Robot Arm.
but when I run
`roslaunch phantomx_reactor_arm_controller arbotix_phantomx_reactor_arm_wrist.launch  `
&
`roslaunch phantomx_reactor_arm_moveit_config demo_real.launch `

it always show :

> [ERROR] [1516936773.761856292]: Joint 'shoulder_pitch_mimic_joint' not found in model 'phantomx_reactor_arm'

> [ERROR] [1516936773.761742310]: Joint 'elbow_pitch_mimic_joint' not found in model 'phantomx_reactor_arm'

How I should Solve it??
I used arm for the first time in Moveit！I really can't do it anymore.

I'm looking forward to your reply.

**Comment by ROM-robotics** [comment]
You can use dynamixel launch file.
